export const kpiData = [
  {
    label: "Active Projects",
    value: "24",
    change: "+3",
    trend: "up",
    icon: "briefcase",
    color: "violet",
  },
  {
    label: "Content Generated",
    value: "1,284",
    change: "+18%",
    trend: "up",
    icon: "sparkles",
    color: "cyan",
  },
  {
    label: "AI Agents Online",
    value: "7 / 8",
    change: "1 idle",
    trend: "neutral",
    icon: "cpu",
    color: "emerald",
  },
  {
    label: "Campaigns Live",
    value: "12",
    change: "+2 this week",
    trend: "up",
    icon: "megaphone",
    color: "pink",
  },
];

export const agents = [
  {
    id: "a1",
    name: "CopyBot Pro",
    role: "Copywriter",
    status: "active",
    task: "Writing product descriptions for TechNova Q3",
    completedTasks: 342,
    avatar: "CB",
    color: "violet",
  },
  {
    id: "a2",
    name: "VisualMind",
    role: "Creative Director",
    status: "active",
    task: "Generating social media assets for EcoWear",
    completedTasks: 219,
    avatar: "VM",
    color: "cyan",
  },
  {
    id: "a3",
    name: "SEO Sage",
    role: "SEO Strategist",
    status: "active",
    task: "Keyword clustering for FinFlow campaign",
    completedTasks: 187,
    avatar: "SS",
    color: "emerald",
  },
  {
    id: "a4",
    name: "DataPulse",
    role: "Analytics Agent",
    status: "active",
    task: "Compiling performance report — Week 22",
    completedTasks: 95,
    avatar: "DP",
    color: "amber",
  },
  {
    id: "a5",
    name: "SocialSync",
    role: "Social Media Manager",
    status: "idle",
    task: "Awaiting content from CopyBot Pro",
    completedTasks: 411,
    avatar: "SY",
    color: "pink",
  },
  {
    id: "a6",
    name: "EmailCraft",
    role: "Email Marketer",
    status: "active",
    task: "A/B testing subject lines for NovaPay",
    completedTasks: 278,
    avatar: "EC",
    color: "blue",
  },
  {
    id: "a7",
    name: "AdBot Alpha",
    role: "Paid Ads Specialist",
    status: "active",
    task: "Optimising Google Ads for MindfulMeals",
    completedTasks: 133,
    avatar: "AA",
    color: "orange",
  },
  {
    id: "a8",
    name: "TrendWatch",
    role: "Trend Analyst",
    status: "processing",
    task: "Scanning trending topics — June 2026",
    completedTasks: 62,
    avatar: "TW",
    color: "rose",
  },
];

export const projects = [
  {
    id: "p1",
    name: "TechNova Q3 Launch",
    client: "TechNova Inc.",
    status: "active",
    progress: 68,
    deadline: "2026-07-15",
    assignedAgents: ["CopyBot Pro", "VisualMind", "SEO Sage"],
    contentItems: 48,
    category: "Product Launch",
  },
  {
    id: "p2",
    name: "EcoWear Brand Refresh",
    client: "EcoWear Co.",
    status: "active",
    progress: 42,
    deadline: "2026-07-30",
    assignedAgents: ["VisualMind", "SocialSync"],
    contentItems: 31,
    category: "Branding",
  },
  {
    id: "p3",
    name: "FinFlow Growth Campaign",
    client: "FinFlow Ltd.",
    status: "review",
    progress: 87,
    deadline: "2026-06-20",
    assignedAgents: ["SEO Sage", "EmailCraft", "AdBot Alpha"],
    contentItems: 62,
    category: "Growth Marketing",
  },
  {
    id: "p4",
    name: "MindfulMeals Q2 Ads",
    client: "MindfulMeals",
    status: "active",
    progress: 55,
    deadline: "2026-06-28",
    assignedAgents: ["AdBot Alpha", "CopyBot Pro"],
    contentItems: 24,
    category: "Paid Advertising",
  },
  {
    id: "p5",
    name: "NovaPay Email Series",
    client: "NovaPay",
    status: "active",
    progress: 30,
    deadline: "2026-08-01",
    assignedAgents: ["EmailCraft", "DataPulse"],
    contentItems: 18,
    category: "Email Marketing",
  },
  {
    id: "p6",
    name: "StyleHub Influencer Kit",
    client: "StyleHub",
    status: "completed",
    progress: 100,
    deadline: "2026-05-31",
    assignedAgents: ["SocialSync", "VisualMind"],
    contentItems: 79,
    category: "Influencer Marketing",
  },
];

export const contentPipeline = [
  {
    id: "c1",
    title: "TechNova Hero Banner Copy",
    type: "Copywriting",
    project: "TechNova Q3 Launch",
    agent: "CopyBot Pro",
    status: "in_progress",
    priority: "high",
    createdAt: "2026-06-05T08:00:00Z",
    dueAt: "2026-06-06T17:00:00Z",
    wordCount: 450,
  },
  {
    id: "c2",
    title: "EcoWear Instagram Carousel (x10)",
    type: "Social Media",
    project: "EcoWear Brand Refresh",
    agent: "VisualMind",
    status: "in_progress",
    priority: "medium",
    createdAt: "2026-06-05T09:30:00Z",
    dueAt: "2026-06-07T12:00:00Z",
    wordCount: 200,
  },
  {
    id: "c3",
    title: "FinFlow SEO Blog Post",
    type: "Blog",
    project: "FinFlow Growth Campaign",
    agent: "SEO Sage",
    status: "review",
    priority: "high",
    createdAt: "2026-06-04T14:00:00Z",
    dueAt: "2026-06-05T18:00:00Z",
    wordCount: 1800,
  },
  {
    id: "c4",
    title: "MindfulMeals Google Ads Headlines",
    type: "Ad Copy",
    project: "MindfulMeals Q2 Ads",
    agent: "AdBot Alpha",
    status: "completed",
    priority: "high",
    createdAt: "2026-06-03T10:00:00Z",
    dueAt: "2026-06-04T17:00:00Z",
    wordCount: 120,
  },
  {
    id: "c5",
    title: "NovaPay Welcome Email Sequence",
    type: "Email",
    project: "NovaPay Email Series",
    agent: "EmailCraft",
    status: "queued",
    priority: "medium",
    createdAt: "2026-06-05T11:00:00Z",
    dueAt: "2026-06-09T17:00:00Z",
    wordCount: 900,
  },
  {
    id: "c6",
    title: "TechNova Product Feature Videos (x3)",
    type: "Video Script",
    project: "TechNova Q3 Launch",
    agent: "CopyBot Pro",
    status: "queued",
    priority: "low",
    createdAt: "2026-06-05T12:00:00Z",
    dueAt: "2026-06-10T17:00:00Z",
    wordCount: 600,
  },
  {
    id: "c7",
    title: "FinFlow Case Study",
    type: "Long-form",
    project: "FinFlow Growth Campaign",
    agent: "SEO Sage",
    status: "completed",
    priority: "medium",
    createdAt: "2026-06-02T09:00:00Z",
    dueAt: "2026-06-04T12:00:00Z",
    wordCount: 2400,
  },
  {
    id: "c8",
    title: "EcoWear Brand Tone Guidelines",
    type: "Strategy Doc",
    project: "EcoWear Brand Refresh",
    agent: "TrendWatch",
    status: "in_progress",
    priority: "low",
    createdAt: "2026-06-05T07:00:00Z",
    dueAt: "2026-06-08T17:00:00Z",
    wordCount: 1200,
  },
];

export const recentOutputs = [
  {
    id: "o1",
    title: "MindfulMeals Google Ads Headlines",
    agent: "AdBot Alpha",
    project: "MindfulMeals Q2 Ads",
    type: "Ad Copy",
    preview:
      "Eat mindfully, live fully. | Delicious meals, delivered with purpose. | Your healthiest habit starts here.",
    completedAt: "2026-06-05T10:45:00Z",
    wordCount: 120,
    rating: 5,
  },
  {
    id: "o2",
    title: "FinFlow Case Study — SME Growth",
    agent: "SEO Sage",
    project: "FinFlow Growth Campaign",
    type: "Long-form",
    preview:
      "How a 12-person accounting firm grew revenue by 340% in 18 months using FinFlow's automation suite...",
    completedAt: "2026-06-04T16:20:00Z",
    wordCount: 2400,
    rating: 4,
  },
  {
    id: "o3",
    title: "StyleHub Influencer Brief Pack",
    agent: "SocialSync",
    project: "StyleHub Influencer Kit",
    type: "Strategy Doc",
    preview:
      "Campaign theme: #WearYourStory. Target: micro-influencers 10k-100k. Aesthetic: editorial, natural lighting...",
    completedAt: "2026-06-03T14:00:00Z",
    wordCount: 3100,
    rating: 5,
  },
];
